-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 23:40:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contacts_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacts_Employers` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Datas_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Datas_Employers` (
  `id` INT NOT NULL,
  `registration` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items_Employers_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Items_Employers_Courses` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employers` (
  `id` INT NOT NULL,
  `name_employer` VARCHAR(45) NULL,
  `Contacts_Employers_id` INT NOT NULL,
  `Datas_Employers_id` INT NOT NULL,
  `Items_Employers_Courses_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Contacts_Employers_id`, `Datas_Employers_id`, `Items_Employers_Courses_id`),
  INDEX `fk_Employers_Contacts_Employers1_idx` (`Contacts_Employers_id` ASC) VISIBLE,
  INDEX `fk_Employers_Datas_Employers1_idx` (`Datas_Employers_id` ASC) VISIBLE,
  INDEX `fk_Employers_Items_Employers_Courses1_idx` (`Items_Employers_Courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employers_Contacts_Employers1`
    FOREIGN KEY (`Contacts_Employers_id`)
    REFERENCES `mydb`.`Contacts_Employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employers_Datas_Employers1`
    FOREIGN KEY (`Datas_Employers_id`)
    REFERENCES `mydb`.`Datas_Employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employers_Items_Employers_Courses1`
    FOREIGN KEY (`Items_Employers_Courses_id`)
    REFERENCES `mydb`.`Items_Employers_Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items_Certifications_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Items_Certifications_Courses` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Types_Courses_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Types_Courses_Employers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `isRequired` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses_Employers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Items_Certifications_Courses_id` INT NOT NULL,
  `Items_Employers_Courses_id` INT NOT NULL,
  `Types_Courses_Employers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Types_Courses_Employers_id`),
  INDEX `fk_Courses_Employers_Items_Certifications_Courses1_idx` (`Items_Certifications_Courses_id` ASC) VISIBLE,
  INDEX `fk_Courses_Employers_Items_Employers_Courses1_idx` (`Items_Employers_Courses_id` ASC) VISIBLE,
  INDEX `fk_Courses_Employers_Types_Courses_Employers1_idx` (`Types_Courses_Employers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Employers_Items_Certifications_Courses1`
    FOREIGN KEY (`Items_Certifications_Courses_id`)
    REFERENCES `mydb`.`Items_Certifications_Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Employers_Items_Employers_Courses1`
    FOREIGN KEY (`Items_Employers_Courses_id`)
    REFERENCES `mydb`.`Items_Employers_Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Employers_Types_Courses_Employers1`
    FOREIGN KEY (`Types_Courses_Employers_id`)
    REFERENCES `mydb`.`Types_Courses_Employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paths_Certifications_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paths_Certifications_Employers` (
  `id` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certifications_Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certifications_Employers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Items_Certifications_Courses_id` INT NOT NULL,
  `Paths_Certifications_Employers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Paths_Certifications_Employers_id`),
  INDEX `fk_Certifications_Employers_Items_Certifications_Courses1_idx` (`Items_Certifications_Courses_id` ASC) VISIBLE,
  INDEX `fk_Certifications_Employers_Paths_Certifications_Employers1_idx` (`Paths_Certifications_Employers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Certifications_Employers_Items_Certifications_Courses1`
    FOREIGN KEY (`Items_Certifications_Courses_id`)
    REFERENCES `mydb`.`Items_Certifications_Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certifications_Employers_Paths_Certifications_Employers1`
    FOREIGN KEY (`Paths_Certifications_Employers_id`)
    REFERENCES `mydb`.`Paths_Certifications_Employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `document_number` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Citys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Citys` (
  `id` INT NOT NULL,
  `name_citys` VARCHAR(45) NULL,
  `Cityscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locations_Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locations_Branch` (
  `id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  `Locations_Branchcol` VARCHAR(45) NULL,
  `Citys_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Citys_id`),
  INDEX `fk_Locations_Branch_Citys1_idx` (`Citys_id` ASC) VISIBLE,
  CONSTRAINT `fk_Locations_Branch_Citys1`
    FOREIGN KEY (`Citys_id`)
    REFERENCES `mydb`.`Citys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Data_Branchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Data_Branchs` (
  `id` INT NOT NULL,
  `social_reason` VARCHAR(45) NULL,
  `fiscal_id` VARCHAR(45) NULL,
  `manager` VARCHAR(45) NULL,
  `Locations_Branch_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Locations_Branch_id`),
  INDEX `fk_Data_Branchs_Locations_Branch1_idx` (`Locations_Branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Branchs_Locations_Branch1`
    FOREIGN KEY (`Locations_Branch_id`)
    REFERENCES `mydb`.`Locations_Branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branchs_Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branchs_Company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Branchs_Companycol` VARCHAR(45) NULL,
  `Managers_id` INT NOT NULL,
  `Data_Branchs_id` INT NOT NULL,
  `Data_Branchs_Locations_Branch_id` INT NOT NULL,
  `Employers_id` INT NOT NULL,
  `Employers_Contacts_Employers_id` INT NOT NULL,
  `Employers_Datas_Employers_id` INT NOT NULL,
  `Employers_Items_Employers_Courses_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Managers_id`, `Data_Branchs_id`, `Data_Branchs_Locations_Branch_id`, `Employers_id`, `Employers_Contacts_Employers_id`, `Employers_Datas_Employers_id`, `Employers_Items_Employers_Courses_id`),
  INDEX `fk_Branchs_Company_Managers1_idx` (`Managers_id` ASC) VISIBLE,
  INDEX `fk_Branchs_Company_Data_Branchs1_idx` (`Data_Branchs_id` ASC, `Data_Branchs_Locations_Branch_id` ASC) VISIBLE,
  INDEX `fk_Branchs_Company_Employers1_idx` (`Employers_id` ASC, `Employers_Contacts_Employers_id` ASC, `Employers_Datas_Employers_id` ASC, `Employers_Items_Employers_Courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Branchs_Company_Managers1`
    FOREIGN KEY (`Managers_id`)
    REFERENCES `mydb`.`Managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Branchs_Company_Data_Branchs1`
    FOREIGN KEY (`Data_Branchs_id` , `Data_Branchs_Locations_Branch_id`)
    REFERENCES `mydb`.`Data_Branchs` (`id` , `Locations_Branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Branchs_Company_Employers1`
    FOREIGN KEY (`Employers_id` , `Employers_Contacts_Employers_id` , `Employers_Datas_Employers_id` , `Employers_Items_Employers_Courses_id`)
    REFERENCES `mydb`.`Employers` (`id` , `Contacts_Employers_id` , `Datas_Employers_id` , `Items_Employers_Courses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`States` (
  `id` INT NOT NULL,
  `name_states` VARCHAR(45) NULL,
  `Citys_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Citys_id`),
  INDEX `fk_States_Citys1_idx` (`Citys_id` ASC) VISIBLE,
  CONSTRAINT `fk_States_Citys1`
    FOREIGN KEY (`Citys_id`)
    REFERENCES `mydb`.`Citys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regions` (
  `id` INT NOT NULL,
  `name_region` VARCHAR(45) NULL,
  `States_id` INT NOT NULL,
  PRIMARY KEY (`id`, `States_id`),
  INDEX `fk_Regions_States1_idx` (`States_id` ASC) VISIBLE,
  CONSTRAINT `fk_Regions_States1`
    FOREIGN KEY (`States_id`)
    REFERENCES `mydb`.`States` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Regions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Regions_id`),
  INDEX `fk_Countries_Regions1_idx` (`Regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Countries_Regions1`
    FOREIGN KEY (`Regions_id`)
    REFERENCES `mydb`.`Regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regions_World`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Regions_World` (
  `id` INT NOT NULL,
  `name_regions` VARCHAR(45) NULL,
  `Countries_id` INT NOT NULL,
  `Countries_Regions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Countries_id`, `Countries_Regions_id`),
  INDEX `fk_Regions_World_Countries1_idx` (`Countries_id` ASC, `Countries_Regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_Regions_World_Countries1`
    FOREIGN KEY (`Countries_id` , `Countries_Regions_id`)
    REFERENCES `mydb`.`Countries` (`id` , `Regions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
